### ISSUE TITLE
Fundamentals data

### ISSUE THREAD

**Issue by DavisVaughan** [business-science/riingo#13]
There is new beta support for fundamentals. If Tiingo gives me access to it, it can be incorporated into riingo https://api.tiingo.com/documentation/fundamentals

**Comment by tiingo** [comment]
Hey Davis,

Happy to set you up! Sent you a note a few days ago - let me know your username and it will be done

Thanks Davis
Rishi

**Comment by DavisVaughan** [comment]
Did you send it to davis @ rstudio.com? I didn't see an email. My username is just `davisvaughan`, thanks!
