### ISSUE TITLE
Currency Pairs

### ISSUE THREAD

**Issue by aegerton** [business-science/riingo#2]
@DavisVaughan I saw your recent tweet in response to a question regarding currency pairs and tried to follow your suggestion as follows;-
```
riingo_crypto_prices("btcjpy", convert_currency = "usd", 
                     resample_frequency = "1min", start_date = "2018-04-05") %>%
  mutate(usdjpy=1/fxRate)
```
Unfortunately, the following error message is received;-
```
Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'fxRate' not found.
In addition: Warning message:
The Tiingo API only uses the first ticker when convert_currency is specified. 
```
Any suggestions as to how I can resolve this error, please?

**Comment by DavisVaughan** [comment]
Can you update to the dev version? There was a small bug I had to fix

devtools::install_github("business-science/riingo")

**Comment by aegerton** [comment]
It works fine with the dev version, thank you @DavisVaughan
