### ISSUE TITLE
Cross-Link to Python Client

### ISSUE THREAD

**Issue by hydrosquall** [business-science/riingo#5]
I've been asked before by R users whether there's an R version of `tiingo-python`, and now I know where to send them!

I've filed an issue to link to `riingo` from our README, and was wondering if you'd be interested in doing the same :)

https://github.com/hydrosquall/tiingo-python/issues/119

**Comment by DavisVaughan** [comment]
Sorry it took me a bit to get to this. Great idea, thanks for the cross link! I've added one back in the README
